### ISSUE TITLE
Seeking Embedded Table functionality

### ISSUE THREAD

**Issue by paladiusdarkhelm** [saif-ellafi/play-by-the-writing#1]
I have many top-level tables that contain other tables. These other tables may also contain results or they may lead to other simple or weighted tables. When rolling manually, you traverse the tables and keep rolling until you reach your result. I'd like for this tool to return the final result of rolling against tables that can contain other tables.

**Comment by saif-ellafi** [comment]
Yes, also needing this. Will do :)

**Comment by saif-ellafi** [comment]
This has been implemented for a while, using `{{table_name}}` you can embed tables within tables in the .txt files!
