### ISSUE TITLE
Problem to make it work in Linux (Manjaro)

### ISSUE THREAD

**Issue by cives** [saif-ellafi/play-by-the-writing#4]
Hi, hola, Jaensen/Saif:
I still do have trouble to make work PBTW in my Linux machine. I even installed a new distro, also derivative from Arch, but the problem is the same.
Espanso works nice, but not PBTW.

Indeed, the PBTW forms do launch the form, but they don't show the result in the terminal or wherever I invoke it. 
> Ya he localizado que el problema de Play by the writing solo surge cuando intenta ejecutar un script. Cuando intenta ejecutar un formulario (form), como en Mythic, entonces sí se ejecuta el formulario, pero no se "renderiza" el resultado.

But the scripts never work at all. They always show this same result.
> El archivo yaml (.yml) del match invoca el script, pero sale el mismo error de siempre:
"[Espanso]: An error occurred during rendering, please examine the logs for more information."

Log results:
21:30:04 [worker(167334)] [WARN] extension 'script' on var: 'output' reported an error: could not execute script: '/home/antoniosp/.config/espanso/scripts/playbtw_core', error: 'No existe el fichero o el directorio (os error 2)'
21:30:04 [worker(167334)] [ERROR] error during rendering: rendering error
Caused by:
    could not execute script: '/home/antoniosp/.config/espanso/scripts/playbtw_core', error: 'No existe el fichero o el directorio (os error 2)'

It does exist the file playbtw_core.py in the scripts directory. 
> Cambié el nombre del script a solo playbtw_core sin extensión. Nada.
Log result:
21:57:40 [worker(170867)] [WARN] extension 'script' on var: 'output' reported an error: could not execute script: '/home/antoniosp/.config/espanso/scripts/playbtw_core.py', error: 'Formato de ejecutable incorrecto (os error 8)'
21:57:40 [worker(170867)] [ERROR] error during rendering: rendering error
Caused by:
    could not execute script: '/home/antoniosp/.config/espanso/scripts/playbtw_core.py', error: 'Formato de ejecutable incorrecto (os error 8)'

Luego modifiqué el yaml de playbtw_core-yml dentro de match, para que llame al script con la extensión playbtw_core.py. Tampoco.
Log result if I change the code in the yml file to direct the order to a file with the py extension, then the log shows...
21:48:51 [worker(169947)] [WARN] extension 'script' on var: 'output' reported an error: could not execute script: '/home/antoniosp/.config/espanso/scripts/playbtw_core.py', error: 'Permiso denegado (os error 13)'
21:48:51 [worker(169947)] [ERROR] error during rendering: rendering error
Caused by:
    could not execute script: '/home/antoniosp/.config/espanso/scripts/playbtw_core.py', error: 'Permiso denegado (os error 13)'
But the file and the folder has all pertinent permissions. I don't get it.

Any idea?

**Comment by saif-ellafi** [comment]
Hola @cives 

No funciona con los archivos de python. Tienes que compilarlo, mira este archivo
https://github.com/saif-ellafi/play-by-the-writing/blob/main/BUILD.md

Ahora compilo en Linux y lo subo a itch.io, para mi no es problema, y agrego el comando para compilar en linux

**Comment by saif-ellafi** [comment]
Listo @cives 

I have uploaded the linux compiled files in https://jeansenvaars.itch.io/play-by-the-writing

Appreciated if you let me know if it works for you :)

**Comment by cives** [comment]
Sure. Thank you.
