### ISSUE TITLE
OpenAI model selector

### ISSUE THREAD

**Issue by PhantomGM** [saif-ellafi/play-by-the-writing#5]
I know i can change it with the Open Source version, but I bought the installable one to show my support for your hard work. Not that I trust myself to do as I'm not a programmer.  So not really an option. Just figured it might be helpful for people who have a trained model or want to use a cheaper model,

**Comment by saif-ellafi** [comment]
Thank you Phantom i really appreciate it. When I get some time I wanted to add more configuration options in OpenAI, such as also the extent of the text, among other things. Unfortunately I am not getting much attention with this application so it is good to know some use it :) :)

**Comment by saif-ellafi** [comment]
This should be fine now
