### ISSUE TITLE
Mythic description doesn’t find its tables

### ISSUE THREAD

**Issue by vonloxley** [saif-ellafi/play-by-the-writing#7]
It looks like the tables for `mde` got renamed to `mythic_descriptor_1.txt` and 'mythic_descriptor_2.txt', the macro is still looking for `mythic_description_1.txt` and `mythic_description_2.txt`, though.

**Comment by saif-ellafi** [comment]
Hey @vonloxley - thank you, but I fixed this a few releases ago, could you please make sure you have the latest version? Both macro and tables should be called "mythic_descriptor_"

Let me know if you figure it out
cheers!

**Comment by vonloxley** [comment]
Ups, my bad! Was still on a commit from 10 days ago. Sorry!
